name: "🤖 機能リクエスト"
description: Copilotを利用してプロジェクトに対する新しい機能を追加する
title: "[CU-XXXX] 機能名"
labels: ["enhancement"]
body:
  - type: textarea
    id: copilot_instructions
    attributes:
      label: "🤖 Copilotが必ず守るべき実装ルール"
      description: "Copilotへの具体的な指示やルールです。Issue（タスク）に合わせて必要に応じて編集・追記してください。"
      value: |
        以下のルールは最優先の制約事項です。いかなる場合も必ず遵守してください。
        - **ガイドラインの遵守**: `.github/copilot-instructions.md` に準拠すること。
        - **ターゲットブランチ**: `xxxx` ブランチに対して実装・修正を行うこと。
        - **言語設定**: Pull Request内の説明、コミットメッセージ、コード内のコメントはすべて「日本語」で記述すること。
        - **ブランチ命名規則**: ブランチを作成する際は、必ず `CU-XXXX` （Issueタイトルのプレフィックスと一致）の名称で作成すること。
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "📖 背景と目的（コンテキスト）"
      description: "現状の課題と、この機能で実現したい目的を記載してください。"
      value: |
        **【現状の課題】**
        （例：現在のシステムでは〇〇ができず、△△の作業に時間がかかっている）
        
        **【機能の目的】**
        （例：〇〇を自動化し、作業効率を向上させたい）
    validations:
      required: true

  - type: textarea
    id: specifications
    attributes:
      label: "✨ 仕様と期待する動作（要件定義）"
      description: "実装すべき機能の詳細を箇条書きで記載してください。"
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "✅ 受け入れ条件（Acceptance Criteria）"
      description: "この機能が完了したと判断できる条件をテスト可能な形で記載してください。"
      value: |
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: true

  - type: checkboxes
    id: target_modules
    attributes:
      label: "📂 対象モジュール"
      description: "該当するモジュールにチェックを入れてください（複数選択可）"
      options:
        - label: "default - ホーム画面、エラーハンドリング (`/default/`)"
        - label: "login - 認証、パスワード管理 (`/login/`)"
        - label: "admission - 入学手続き管理 (`/admission/`)"
        - label: "student - 学籍情報管理 (`/student/`)"
        - label: "lesson - 履修・カリキュラム・シラバス管理 (`/lesson/`)"
        - label: "cuext - 公開学習（エクステンション） (`/cuext/`)"
        - label: "system - システム管理（お知らせ、イベント等） (`/system/`)"

  - type: textarea
    id: file_info
    attributes:
      label: "📄 実装対象・参照ファイル情報"
      description: "Copilotが作成・修正するファイルや、参考にすべき既存実装のパスを記載してください。"
      value: |
        **【新規作成・変更するファイル】**
        - 
        
        **【参考にすべき既存実装（コーディングパターン）】**
        - Controller: `例: controllers/admission/Admission_StatusController.php`
        - Model: `例: models/admission/Admission_StatusModel.php`
        - Template: `例: smarty/templates/admission/status/status.html`
    validations:
      required: false

  - type: textarea
    id: constraints
    attributes:
      label: "⚠️ 制約事項・非機能要件"
      description: "セキュリティ、パフォーマンス、互換性などの制約があれば記載してください"
      placeholder: |
        - 既存のXXX機能との互換性を保つこと
        - レスポンスタイムは3秒以内であること
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: "📎 追加情報"
      description: "スクリーンショット、モックアップ、参考URLなど、その他の補足情報を記載してください"
      placeholder: |
        - スクリーンショット: (画像を貼り付け)
        - 参考URL: https://...
    validations:
      required: false